language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script: 
  - "flake8 --ignore=E501,F403 app tests "
# command to run tests
script: 
  - lettuce tests
  - coverage run --omit='*lettuce*,*fuzzywuzzy*' tests/features/steps.py
  - coverage report -m
  - nosetests --with-doctest --with-coverage -s app
